# Generated by Django 5.1.7 on 2025-03-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=100, unique=True)),
                ('document_hash', models.TextField()),
                ('signer_id', models.CharField(max_length=100)),
                ('signature', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
            ],
        ),
    ]
